In [2]:
import numpy as np

In [3]:
# Create a sample 2D array (5 rows, 4 columns)
array_2d = np.array([[ 1,  2,  3,  4],
                      [ 5,  6,  7,  8],
                      [ 9, 10, 11, 12],
                      [13, 14, 15, 16],
                      [17, 18, 19, 20]])


In [5]:
print(array_2d[2:5,0:2])

[[ 9 10]
 [13 14]
 [17 18]]


In [6]:
# Create two sample 2D arrays (e.g., grayscale images)
img1 = np.array([[1, 2], [3, 4]])  # Shape (2, 2)
img2 = np.array([[5, 6], [7, 8]])  # Shape (2, 2)

# Using np.append without specifying axis
result = np.append(img1, img2)
print("Result without specifying axis:")
print(result)
print("Shape:", result.shape)


Result without specifying axis:
[1 2 3 4 5 6 7 8]
Shape: (8,)


In [13]:
img1 = np.array([[1, 2], [3, 4]])  # Shape (2, 2)
img2 = np.array([[5, 6], [7, 8]])  # Shape (2, 2)
# img2 = np.array([[5, 6], [7, 8, 9]])  # Shape (2, 2)
# img2 = np.array([[5, 6], [7, 8], [9, 10]])  # Shape (2, 2)

# Using np.append without specifying axis
result = np.append(img1, img2, axis=1)
print("Result without specifying axis:")
print(result)
print("Shape:", result.shape)

Result without specifying axis:
[[1 2 5 6]
 [3 4 7 8]]
Shape: (2, 4)


In [10]:
print(result[3:,1])

[ 8 10]


#### array[start_row:end_row, start_column:end_column]


In [33]:
result[3:4,1]

array([8])

In [11]:
# Create two sample color images (3D arrays)
# Image 1 (2x2 pixels, 3 color channels)
img1 = np.array([[[255, 0, 0], [255, 0, 0]],  # Red color
                  [[0, 255, 0], [0, 255, 0]]])  # Green color

# Image 2 (2x2 pixels, 3 color channels)
img2 = np.array([[[0, 0, 255], [0, 0, 255]],  # Blue color
                  [[255, 255, 0], [255, 255, 0]]])  # Yellow color


In [9]:
# Concatenate vertically (add rows)
result_vertical = np.append(img1, img2, axis=0)
print("Result with vertical concatenation (axis=0):")
print(result_vertical)
print("Shape:", result_vertical.shape)


Result with vertical concatenation (axis=0):
[[[255   0   0]
  [255   0   0]]

 [[  0 255   0]
  [  0 255   0]]

 [[  0   0 255]
  [  0   0 255]]

 [[255 255   0]
  [255 255   0]]]
Shape: (4, 2, 3)


In [42]:
extracted_img1 = result_vertical[1:3:]
extracted_img1

array([[[  0, 255,   0],
        [  0, 255,   0]],

       [[  0,   0, 255],
        [  0,   0, 255]]])

In [16]:
def myFun(*argv):
    for arg in argv:
        print(arg)
myFun('Hello', 'Welcome', 'to', 'GeeksforGeeks')


Hello
Welcome
to
GeeksforGeeks


In [18]:
def myFun(argv):
    for arg in argv:
        print(arg)
myFun(['Hello', 'Welcome', 'to', 'GeeksforGeeks'])


Hello
Welcome
to
GeeksforGeeks


In [22]:
target_size = (100, 100)
gray_imgs = np.empty((0, *target_size))  # Initialize empty array with target size
gray_imgs

array([], shape=(0, 100, 100), dtype=float64)

In [23]:
import numpy as np

# Example arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Using np.append
appended_array = np.append(arr1, arr2, axis=0)  # This will flatten both arrays if axis=None
print("Using np.append:")
print(appended_array)

# Using np.vstack
stacked_array = np.vstack((arr1, arr2))  # Stacks vertically
print("\nUsing np.vstack:")
print(stacked_array)


Using np.append:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Using np.vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
